[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
memory = "512MB"  # 메모리 제한 설정
concurrency = 5  # 동시 요청 제한
deployHealthcheckEnabled = true
deployHealthcheckPath = "/health"

[envs]
MALLOC_ARENA_MAX = "2"
PYTHONMALLOC = "malloc"
PYTHONDONTWRITEBYTECODE = "1" 