[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
numReplicas = 1  # 단일 인스턴스로 시작
memory = "1024MB"  # Metal에서는 더 많은 메모리 할당 가능
deployHealthcheckPath = "/health"

# Metal에서는 CPU 코어 수도 지정 가능
[resources]
cpuCount = 1  # CPU 코어 수
memoryMB = 1024  # 메모리(MB)

[envs]
MALLOC_ARENA_MAX = "2"
PYTHONMALLOC = "malloc"
PYTHONDONTWRITEBYTECODE = "1" 